BelozertsevVS/RBDMS-EA-EK-22

LW2/BielozertsevLW2.sql
=> BielozertsevLW2

LW2/Hryhorieva_Polina_LW_2.sql
=> Hryhorieva_Polina_LW_2

LW3/Hryhorieva_Polina_LW_3.sql
=> Hryhorieva_Polina_LW_3

LW4/Hryhorieva_Polina_LW_4.sql
=> Hryhorieva_Polina_LW_4

LW3/ProtsKiraLW3.sql
=> ProtsKiraLW3

LW6/Hryhorieva_Polina_LW_6.sql
=> Hryhorieva_Polina_LW_6

LW6/ProtsKiraLW6.sql
=> ProtsKiraLW6

LW6/SolomyanaLW6.sql
=> SolomyanaLW6

LW4/ProtsKiraLW4.sql
=> ProtsKiraLW4

LW7/SolomyanaLW7.sql
=> SolomyanaLW7

LW8/ProtsKiraLW8.sql
=> ProtsKiraLW8

LW7/ProtsKiraLW7.sql
=> ProtsKiraLW7

LW7/Hryhorieva_Polina_LW_7.sql
=> Hryhorieva_Polina_LW_7

LW8/Hryhorieva_Polina_LW_8.sql
=> Hryhorieva_Polina_LW_8

LW12/IovovaLW12.sql
=> IovovaLW12

LW14/IovovaLW14.sql
=> IovovaLW14

LW13/ProtsKiraLW13.sql
=> ProtsKiraLW13

LW14/SolomyanaLW14.sql
=> SolomyanaLW14

LW13/Hryhorieva_Polina_LW_13.sql
=> Hryhorieva_Polina_LW_13

LW15/SolomyanaLW15.sql
=> SolomyanaLW15

LW16/Hryhorieva_Polina_LW_16.sql
=> Hryhorieva_Polina_LW_16

LW16/IovovaLW16.sql
=> IovovaLW16

LW17/IovovaLW17.sql
=> IovovaLW17

LW18/IovovaLW18.sql
=> IovovaLW18

LW17/SoolomyanaLW17.sql
=> SolomyanaLW17

LW16/SolomyanaLW16.sql
=> SolomyanaLW16

LW18/SolomyanaLW18.sql
=> SolomyanaLW18

LW15/ProtsKiraLW15.sql
=> ProtsKiraLW15

LW4/Kutsevol_LW4.sql
=> Kutsevol_LW4

LW3/Kutsevol_LW3.sql
=> Kutsevol_LW3

LW3/KlymenkoLW3.sql
=> KlymenkoLW3

LW17/Hryhorieva_Polina_LW_17.sql
=> Hryhorieva_Polina_LW_17

LW17/ProtsKiraLW17.sql
=> ProtsKiraLW17

LW18/ProtsKiraLW18.sql
=> ProtsKiraLW18

LW19/IovovaLW19.sql
=> IovovaLW19

LW20/IovovaLW20.sql
=> IovovaLW20

LW19/SolomyanaLW19.sql
=> SolomyanaLW19

LW20/SolomyanaLW20.sql
=> SolomyanaLW20

LW20/ProtsKiraLW20.sql
=> ProtsKiraLW20

LW19/ProtsKiraLW19.sql
=> ProtsKiraLW19

LW19/Hryhorieva_Polina_LW_19.sql
=> Hryhorieva_Polina_LW_19

LW18/Hryhorieva_Polina_LW_18.sql
Hryhorieva_Polina_LW_18
Виникли певні проблеми з кодуванням файлу.
=> Hryhorieva_Polina_LW_18

LW20/Hryhorieva_Polina_LW_20.sql
=> Hryhorieva_Polina_LW_20

LW16/Andreev Artem LW16.sql
=> Andreev Artem LW16
